/* Project tools use the same revisioned command API as the assistant. */
function cloudSync(){
 const approved=live('assets').filter(a=>a.review==='approved');
 $('#content').innerHTML=`<div class="panel"><h2>Reviewed assets to Higgsfield</h2><p>This adapter uploads selected media to the documented Higgsfield API and saves reusable input URLs. It does not create a native Cinema Studio project, synchronize its timeline, or submit paid generation. Prepare an assistant handoff plan for project assembly through supported connector tools.</p><div class="toolbar"><button id="sync-plan">Prepare assistant handoff plan</button><button id="sync-config">Configure API credentials</button><button id="sync-forget">Forget credentials</button></div></div><div class="panel" style="margin-top:20px"><h2>Approved assets</h2>${approved.map(a=>`<label class="row"><span><input type="checkbox" name="sync-asset" value="${a.id}"> ${esc(a.name)}</span><span class="pill">${(project.cloud_assets||[]).some(r=>r.sha256===a.sha256)?'Previously uploaded':'Local only'}</span></label>`).join('')||'<p>Approve assets in the Asset library first.</p>'}<label class="field"><span><input id="sync-refresh" type="checkbox"> Re-upload selected files to refresh provider-managed input URLs</span></label><button id="sync-upload" class="primary">Upload selected assets to Higgsfield</button><p class="muted">This sends files outside your computer. API credentials stay in this portable folder and are excluded from project exports. Cloud uploads require your own developer API account.</p></div><div class="panel" style="margin-top:20px"><h2>Upload receipts</h2><pre>${esc(JSON.stringify(project.cloud_assets||[],null,2))}</pre></div>`;
 bind('#sync-plan',()=>command('cloud/plan'));
 bind('#sync-config',()=>modal('Local Higgsfield API credentials',field('key','API key ID','','text','required autocomplete="off"')+field('secret','API key secret','','password','required autocomplete="new-password"')+'<p class="field wide">Stored in User/higgsfield-api.json inside this portable installation. Do not share that folder. These credentials are not included in VISION exports.</p>',v=>command('cloud/configure',v)));
 bind('#sync-forget',()=>command('cloud/forget'));
 bind('#sync-upload',()=>command('cloud/upload',{assets:[...document.querySelectorAll('[name=sync-asset]:checked')].map(e=>e.value),confirm_upload:true,refresh:$('#sync-refresh').checked}));
}

function masked(){
 $('#content').innerHTML=`<p>Paint the area to replace, then describe the change. Qwen edits the reference image; a final mask composite preserves pixels outside your painted and feathered region. Start ComfyUI before staging.</p><div class="toolbar"><select id="mask-image" style="max-width:420px">${options(live('assets').filter(a=>a.kind==='image'))}</select><label>Brush <input id="mask-brush" type="range" min="5" max="200" value="60"></label><label><input id="mask-erase" type="checkbox"> Erase</label><button id="mask-clear">Clear mask</button><button id="mask-all">Select all</button></div><div class="panel"><canvas id="mask-canvas" style="max-width:100%;max-height:600px;touch-action:none;cursor:crosshair"></canvas></div><label class="field">Edit instruction<textarea id="mask-prompt" placeholder="Change the shirt to turquoise, preserving its texture and shape."></textarea></label><div class="toolbar"><label>Feather pixels<input id="mask-feather" type="number" min="0" max="64" value="8"></label><label>Seed<input id="mask-seed" type="number" min="0" value="42"></label><button id="mask-stage" class="primary">Stage visible editing workflow</button></div>`;
 const canvas=$('#mask-canvas'),ctx=canvas.getContext('2d'),mask=document.createElement('canvas'),m=mask.getContext('2d');let image=null,last=null;
 function draw(){if(!image)return;ctx.drawImage(image,0,0);ctx.save();ctx.globalAlpha=.45;ctx.drawImage(mask,0,0);ctx.restore();}
 $('#mask-image').onchange=safe(async()=>{image=new Image();image.src=url(find('assets',$('#mask-image').value));await image.decode();canvas.width=mask.width=image.width;canvas.height=mask.height=image.height;m.fillStyle='black';m.fillRect(0,0,mask.width,mask.height);draw();});
 const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height];};
 function paint(e){if(!last||!image)return;const p=point(e);m.strokeStyle=$('#mask-erase').checked?'black':'white';m.lineWidth=Number($('#mask-brush').value);m.lineCap='round';m.beginPath();m.moveTo(...last);m.lineTo(...p);m.stroke();last=p;draw();}
 canvas.onpointerdown=e=>{last=point(e);canvas.setPointerCapture(e.pointerId);paint(e);};canvas.onpointermove=paint;canvas.onpointerup=()=>last=null;canvas.onpointercancel=()=>last=null;
 bind('#mask-clear',()=>{m.fillStyle='black';m.fillRect(0,0,mask.width,mask.height);draw();});bind('#mask-all',()=>{m.fillStyle='white';m.fillRect(0,0,mask.width,mask.height);draw();});
 bind('#mask-stage',async()=>{if(!image)throw Error('Choose an image');await command('masked-edit',{image:$('#mask-image').value,mask:mask.toDataURL('image/png'),prompt:$('#mask-prompt').value,seed:Number($('#mask-seed').value),feather:Number($('#mask-feather').value)});location.hash='workflows';});
}

function voices(){
 $('#content').innerHTML=`<p>Reusable Qwen3 voice profiles run locally. Generated scripts are saved with each take; use Dialogue & subtitles to transcribe and review actual timing.</p><div class="toolbar"><button id="new-voice" class="primary">Create voice</button></div><div class="grid">${(project.voices||[]).map(v=>`<article class="card" data-voice="${v.id}"><h3>${esc(v.name)}</h3><p>${esc(v.speaker)} · ${esc(v.instruct)}</p><div class="actions"></div></article>`).join('')}</div><div class="panel" style="margin-top:24px"><h2>Portrait lip-sync</h2><p>MuseTalk animates a still portrait using recorded or generated speech. Draw a rectangle around the face, including the forehead and chin. Cartoon articulation and identity need visual review. Moving-camera footage and automatic face tracking are not supported.</p><label class="field">Portrait<select id="lip-image">${options(live('assets').filter(a=>a.kind==='image'))}</select></label><label class="field">Speech, up to 30 seconds<select id="lip-audio">${options(live('assets').filter(a=>a.audio&&a.duration<=30))}</select></label><canvas id="lip-canvas" style="max-width:100%;max-height:500px;touch-action:none;cursor:crosshair"></canvas><p id="lip-box">Select a portrait and draw the face region.</p><button id="lip-run" class="primary">Generate lip-sync locally</button></div>`;
 function edit(v={}){modal('Voice profile',field('name','Profile name',v.name,'text','required')+select('speaker','Base speaker',options(['Vivian','Serena','Uncle_Fu','Dylan','Eric','Ryan','Aiden','Ono_Anna','Sohee'].map(id=>({id,name:id})),v.speaker||'Ryan',null))+field('instruct','Performance direction',v.instruct,'textarea')+field('seed','Seed',v.seed??42,'number'),x=>command('advanced/voice-save',{id:v.id,value:{...x,seed:Number(x.seed)}}));}
 bind('#new-voice',()=>edit());
 for(const v of project.voices||[])addButtons($(`[data-voice="${v.id}"] .actions`),[['Edit',()=>edit(v)],['Record dialogue',()=>modal('Generate speech · '+v.name,field('text','Spoken dialogue','','textarea','required maxlength="2000"'),x=>command('advanced/speak',{voice:v.id,text:x.text}))]]);
 let box=null,start=null,image=null;const canvas=$('#lip-canvas'),ctx=canvas.getContext('2d');
 function draw(){if(!image)return;ctx.drawImage(image,0,0,canvas.width,canvas.height);if(box){ctx.strokeStyle='#86f6ff';ctx.lineWidth=3;ctx.strokeRect(box[0]*canvas.width,box[1]*canvas.height,(box[2]-box[0])*canvas.width,(box[3]-box[1])*canvas.height);}}
 $('#lip-image').onchange=safe(async()=>{box=null;image=new Image();image.src=url(find('assets',$('#lip-image').value));await image.decode();canvas.width=Math.min(700,image.width);canvas.height=Math.round(canvas.width*image.height/image.width);draw();});
 const point=e=>{const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
 canvas.onpointerdown=e=>{start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const end=point(e);box=[Math.min(start[0],end[0]),Math.min(start[1],end[1]),Math.max(start[0],end[0]),Math.max(start[1],end[1])];draw();};canvas.onpointerup=()=>{start=null;$('#lip-box').textContent=box?'Face region selected.':'Draw a face rectangle.';};
 bind('#lip-run',()=>{if(!box)throw Error('Draw a face rectangle first');return command('advanced/lipsync',{image:$('#lip-image').value,audio:$('#lip-audio').value,box});});
}

async function sets3d(){
 $('#content').innerHTML=`<p>Block out sets, props and camera composition. Save editable scenes, render locally with portable Blender, and use the resulting images as generation references.</p><div class="toolbar"><select id="set-select" style="max-width:320px">${options(project.sets3d||[],'','New scene')}</select><button id="set-save" class="primary">Save scene</button><button id="set-render">Render in Blender</button><button id="blender-launch">Open portable Blender</button></div><div class="columns"><div class="panel"><div id="set-viewport" style="height:480px"></div><p class="muted">Drag to orbit · scroll to zoom · right-drag to pan. Camera capture uses the viewport composition.</p><button id="set-camera">Use this camera angle</button></div><div class="panel"><label class="field">Scene name<input id="set-name" value="New set"></label><div class="toolbar"><select id="set-shape"><option>cube</option><option>sphere</option><option>cylinder</option><option>cone</option><option>plane</option></select><button id="set-add">Add object</button></div><label class="field">Objects<select id="set-object"></select></label><div id="set-properties"></div><button id="set-delete">Remove object</button><label class="field">Render size<select id="set-size"><option value="640,360">640 × 360 draft</option><option value="1280,720">1280 × 720</option><option value="1920,1080">1920 × 1080</option></select></label><label class="field">Lens (mm)<input id="set-lens" type="number" min="10" max="300" value="50"></label><label class="field">Key light power<input id="set-power" type="number" min="1" max="10000" value="1200"></label></div></div><div id="blend-results" class="grid" style="margin-top:24px"></div>`;
 const owner=$('#set-viewport');
 const THREE=await import('three'),{OrbitControls}=await import('/studio-file/Studio/vendor/three/OrbitControls.js');if(current!=='sets3d'||owner!==$('#set-viewport'))return;
 const viewport=$('#set-viewport'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(viewport.clientWidth,viewport.clientWidth*9/16);renderer.setPixelRatio(Math.min(devicePixelRatio,2));viewport.style.height=(viewport.clientWidth*9/16)+'px';viewport.append(renderer.domElement);
 const world=new THREE.Scene();world.background=new THREE.Color('#140d20');const camera=new THREE.PerspectiveCamera(40,16/9,.01,2000);camera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);
 const group=new THREE.Group();world.add(group);world.add(new THREE.HemisphereLight(0xffffff,0x493449,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(4,-4,8);world.add(light);
 const grid=new THREE.GridHelper(20,20,0x734a83,0x362c42);grid.rotation.x=Math.PI/2;world.add(grid);
 let draft,key='';
 function fresh(){return {name:'New set',width:640,height:360,objects:[{id:crypto.randomUUID(),name:'Ground',type:'plane',position:[0,0,0],scale:[12,12,1],rotation:[0,0,0],color:'#b89e76'}],lights:[{name:'Key',position:[4,-4,8],target:[0,0,0],power:1200,size:5,color:'#ffffff'}],camera:{position:[7,-10,6],target:[0,0,1],lens:50}};}
 function meshes(){for(const m of [...group.children]){m.geometry.dispose();m.material.dispose();group.remove(m);}for(const o of draft.objects){let g;if(o.type==='cube')g=new THREE.BoxGeometry(1,1,1);if(o.type==='sphere')g=new THREE.SphereGeometry(.5,32,16);if(o.type==='plane')g=new THREE.PlaneGeometry(1,1);if(o.type==='cylinder'||o.type==='cone'){g=new THREE.CylinderGeometry(o.type==='cone'?0:.5,.5,1,32);g.rotateX(Math.PI/2);}const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:o.color,side:THREE.DoubleSide}));m.position.fromArray(o.position);m.scale.fromArray(o.scale);m.rotation.set(...o.rotation.map(v=>v*Math.PI/180));group.add(m);}renderer.render(world,camera);}
 function properties(){const o=draft.objects.find(o=>o.id===$('#set-object').value);$('#set-properties').innerHTML=o?field('object-name','Name',o.name)+field('object-color','Color',o.color,'color')+['position','scale','rotation'].map(k=>field('object-'+k,k+' · X, Y, Z',o[k].join(', '))).join(''):'';for(const input of $('#set-properties').querySelectorAll('input'))input.onchange=safe(()=>{const k=input.name.slice(7);if(['position','scale','rotation'].includes(k)){const values=input.value.split(',').map(Number);if(values.length!==3||values.some(v=>!Number.isFinite(v))||(k==='scale'&&values.some(v=>v<=0)))throw Error('Enter three valid numbers separated by commas');o[k]=values;}else o[k]=input.value;meshes();});}
 function objects(selected){$('#set-object').innerHTML=options(draft.objects,selected||draft.objects.at(-1)?.id,null);properties();meshes();}
 function loadSet(){key=$('#set-select').value;draft=structuredClone((project.sets3d||[]).find(s=>s.id===key)||fresh());$('#set-name').value=draft.name;$('#set-size').value=[draft.width,draft.height].join(',');$('#set-lens').value=draft.camera.lens;$('#set-power').value=draft.lights[0].power;camera.position.fromArray(draft.camera.position);controls.target.fromArray(draft.camera.target);camera.setFocalLength(draft.camera.lens);controls.update();objects();}
 $('#set-select').onchange=loadSet;$('#set-object').onchange=properties;loadSet();controls.addEventListener('change',()=>renderer.render(world,camera));
 bind('#set-add',()=>{draft.objects.push({id:crypto.randomUUID(),name:$('#set-shape').value,type:$('#set-shape').value,position:[0,0,.5],rotation:[0,0,0],scale:[1,1,1],color:'#e94393'});objects();});
 bind('#set-delete',()=>{draft.objects=draft.objects.filter(o=>o.id!==$('#set-object').value);objects();});
 $('#set-lens').onchange=()=>{camera.setFocalLength(Number($('#set-lens').value));renderer.render(world,camera);};
 bind('#set-camera',()=>{draft.camera.position=camera.position.toArray();draft.camera.target=controls.target.toArray();notice('Camera angle captured; save the scene to keep it.');});
 async function save(){draft.name=$('#set-name').value;[draft.width,draft.height]=$('#set-size').value.split(',').map(Number);draft.camera.lens=Number($('#set-lens').value);draft.lights[0].power=Number($('#set-power').value);const r=await command('advanced/scene-save',{id:key||undefined,value:draft},false);key=key||r.project.sets3d.at(-1).id;$('#set-select').innerHTML=options(project.sets3d,key,'New scene');return key;}
 bind('#blender-launch',()=>command('advanced/blender-launch',{},false));bind('#set-save',save);bind('#set-render',async()=>{const scene=await save();await command('advanced/blender-render',{scene},false);});
 for(const j of project.jobs.filter(j=>['blender-render','blender-rerender'].includes(j.type)&&['complete','imported'].includes(j.status))){const card=document.createElement('article');card.className='card';card.innerHTML=`${j.result.file?`<img src="/studio-file/${encodeURI(j.result.file)}" alt="Blender render">`:""}<p>Editable Blender scene</p>`;card.append(button('Edit in portable Blender',()=>command('advanced/blender-open',{job:j.id},false)),button('Re-render saved Blender edits',()=>command('advanced/blender-rerender',{job:j.id},false)));$('#blend-results').append(card);}
 const cleanup=()=>{controls.dispose();renderer.dispose();group.children.forEach(m=>{m.geometry.dispose();m.material.dispose();});};const observer=new MutationObserver(()=>{if(!viewport.isConnected){cleanup();observer.disconnect();}});observer.observe($('#content'),{childList:true});
}
