let agentState=null,agentProject='',agentPolling=false;
async function agentCall(action,data={}){const result=await api('/api/agent/'+action,{project:project.id,...data});agentState=result;drawAgentRun();return result;}
async function mountAgent(){
 const key=project.id;agentState=await api('/api/agent/state/'+key);if(current!=='ai'||project.id!==key)return;agentProject=key;
 const s=agentState.settings;
 $('#agent-panel').innerHTML=`<div class="panel" style="margin-bottom:20px;border-color:#b53c85"><h2>Local AI agent</h2><p>Plan first. Work stays in this project; cloud actions and access outside the studio are unavailable to the agent.</p><div class="toolbar agent-settings"><label><input id="agent-enabled" type="checkbox" ${s.enabled?'checked':''}> Enable agent</label><label>Autonomy<select id="agent-mode"><option value="ask">Ask for approval · each step</option><option value="routine">Approve routine actions · one plan approval</option><option value="full">Full local autonomy · within limits</option></select></label><label>Brain<select id="agent-model"><option value="normal">Normal · Qwen 27B</option><option value="heretic">Heretic · Qwen 27B</option><option value="light">Light · Qwen 8B</option></select></label><label>Max generations per request<input id="agent-limit" type="number" min="0" max="8" value="${s.max_generations}"></label><label><input id="agent-laya" type="checkbox" ${s.use_laya?'checked':''}> Consult Laya (experimental)</label><button id="agent-settings">Save autonomy settings</button></div><p class="muted">Agent requests use the message box below. It can edit world elements, scenes, shots and timelines; run installed Krea/H3 presets visibly; render timelines and transcribe assets. It cannot visually judge artwork, train models, execute arbitrary workflows or call every studio tool yet. Full autonomy executes a bounded plan, not an unlimited retry loop.</p><div id="agent-run"></div></div>`;
 $('#agent-mode').value=s.mode;$('#agent-model').value=s.model;
 bind('#agent-settings',async()=>{await agentCall('settings',{settings:{enabled:$('#agent-enabled').checked,mode:$('#agent-mode').value,model:$('#agent-model').value,max_generations:Number($('#agent-limit').value),use_laya:$('#agent-laya').checked}});notice('Autonomy settings saved for this project.');});drawAgentRun();
}
async function sendAgentRequest(prompt){
 const state=await api('/api/agent/state/'+project.id);if(!state.settings.enabled)return false;
 await agentCall('plan',{prompt});notice(state.settings.mode==='full'?'Planning and executing within saved local limits.':'Preparing a short plan. No project edits until approval.');return true;
}
function drawAgentRun(){
 if(current!=='ai'||!$('#agent-run')||agentProject!==project.id)return;
 const r=agentState.run,host=$('#agent-run');
 const signature=JSON.stringify(agentState);if(host.dataset.signature===signature)return;host.dataset.signature=signature;
 if(!r){host.innerHTML='<p>Send a request below, such as “Create a friendly robot and generate two design options.”</p>';return;}
 host.innerHTML=`<div class="row"><strong>${esc(r.request)}</strong><span class="pill">${esc(r.status.replaceAll('_',' '))}</span></div>${r.error?`<p class="error">${esc(r.error)}</p>`:''}${r.plan?`<h3>${esc(r.plan.summary)}</h3><p>${r.plan.generations} generation(s) · ${r.cursor}/${r.plan.steps.length} steps complete · model ${esc(r.model||'local')} · project revision ${r.expected_revision}</p><ol>${r.plan.steps.map((s,i)=>`<li style="margin:12px 0"><strong>${i<r.cursor?'✓ ':''}${esc(s.description)}</strong><details><summary>Exact proposed ${esc(s.action)} parameters</summary><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(JSON.stringify(s.data,null,2))}</pre></details></li>`).join('')}</ol>`:''}<div class="toolbar" id="agent-buttons"></div><details><summary>Activity and model usage</summary><pre style="white-space:pre-wrap">${esc((r.events||[]).map(e=>new Date(e.at*1000).toLocaleTimeString()+' · '+e.message).join('\n'))}</pre><p>${esc(JSON.stringify(r.usage||{}))}</p>${r.laya?`<pre style="white-space:pre-wrap">Laya advisory: ${esc(JSON.stringify(r.laya,null,2))}</pre>`:''}</details><p class="muted">Pause/Stop waits for the current job to finish. Undo restores project edits only when no later edits conflict; generated assets and job evidence are retained.</p>`;
 const buttons=$('#agent-buttons');
 if(!agentState.busy&&['awaiting_approval','paused'].includes(r.status))buttons.append(button(r.cursor?'Approve next / resume':'Approve plan',()=>agentCall('approve',{run:r.id}),'primary'));
 if(!agentState.busy&&r.status==='awaiting_approval'&&!r.cursor)buttons.append(button('Edit plan',()=>modal('Edit proposed plan',field('plan','Plan JSON',JSON.stringify({summary:r.plan.summary,steps:r.plan.steps},null,2),'textarea'),v=>agentCall('edit',{plan:JSON.parse(v.plan)}))));
 if(!agentState.busy&&r.status==='awaiting_approval'&&!r.cursor)buttons.append(button('Revise request',()=>modal('Revise the request and plan again',field('request','What should the agent do?',r.request,'textarea'),async v=>{await agentCall('cancel');await agentCall('plan',{prompt:v.request});})));
 if(['planning','running'].includes(r.status))buttons.append(button('Pause after current job',()=>agentCall('pause')));
 if(!['complete','cancelled','undone','failed','stale'].includes(r.status))buttons.append(button('Stop / cancel',()=>agentCall('cancel')));
 if(!agentState.busy&&r.cursor&&r.status!=='undone')buttons.append(button('Undo project edits',async()=>{await agentCall('undo');project=await api('/api/studio/project/'+project.id);projectsMenu();}));
 if(['complete','failed','cancelled','stale','undone'].includes(r.status))buttons.append(button('Reload project state',()=>load(project.id)));
}
async function pollAgent(){if(current!=='ai'||!project||agentPolling)return;agentPolling=true;const key=project.id;try{const state=await api('/api/agent/state/'+key);if(current==='ai'&&project.id===key){agentState=state;if(state.run&&state.run.expected_revision!==project.revision){const fresh=await api('/api/studio/project/'+key);if(project.id===key){project=fresh;projectsMenu();}}drawAgentRun();}}catch(e){notice(e.message,true);}finally{agentPolling=false;}}
setInterval(pollAgent,2000);
